### ISSUE TITLE
Please support the flycheck-color-mode-line

### ISSUE THREAD

**Issue by ReimuXMX** [dudleyf/color-theme-github#8]
I use the `flycheck-color-mode-line`, but in your theme. It doesn't work.

Or ... it does not have any change in your theme.

Thanks.

**Comment by dudleyf** [comment]
I haven't used Emacs seriously in years, so I'm not going to be able to fix it, sorry. I've added a note to the readme stating it's unmaintained.

**Comment by yuzumx** [comment]
Thanks.
